package cli

import (
	"github.com/daxchain-io/daxie/internal/domain"
	"github.com/spf13/cobra"
)

// newCompletionCmd builds `daxie completion bash|zsh|fish`.
//
// It emits a shell completion script on stdout for the named shell, generated by
// Cobra from the actual command tree (so it never drifts from the real flags).
// PowerShell is intentionally omitted in M0 — the documented surface is the three
// POSIX shells (cli-spec §Utility); a missing/unknown shell is a usage error.
//
// This command does not respect --json (a completion script is shell source, not
// data) and opens no service. Exit codes: 0 on success; 2 (usage) on an unknown
// or missing shell argument.
func newCompletionCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:       "completion [bash|zsh|fish]",
		Short:     "Generate a shell completion script",
		Long:      "Output a completion script for the given shell. Source it from your shell rc.\n\nExamples:\n  daxie completion zsh  > \"${fpath[1]}/_daxie\"\n  daxie completion bash > /etc/bash_completion.d/daxie\n  daxie completion fish > ~/.config/fish/completions/daxie.fish",
		ValidArgs: []string{"bash", "zsh", "fish"},
		Args:      cobra.MatchAll(cobra.ExactArgs(1), cobra.OnlyValidArgs),
		RunE: func(cmd *cobra.Command, args []string) error {
			out := cmd.OutOrStdout()
			root := cmd.Root()
			switch args[0] {
			case "bash":
				return wrapGen(root.GenBashCompletionV2(out, true))
			case "zsh":
				return wrapGen(root.GenZshCompletion(out))
			case "fish":
				return wrapGen(root.GenFishCompletion(out, true))
			default:
				// Unreachable given ValidArgs, but kept explicit for honesty.
				return domain.Newf("usage.completion.unknown_shell", "unknown shell %q (want bash|zsh|fish)", args[0])
			}
		},
	}
	return cmd
}

// wrapGen turns a generator's raw error (an I/O failure writing the script) into
// a typed internal error so it funnels through the registry like everything else.
func wrapGen(err error) error {
	if err == nil {
		return nil
	}
	return domain.Wrap("internal", "failed to write completion script", err)
}
